blank_issues_enabled: true
contact_links:
  - name: Read the Documentation
    url: https://docs.copilot.ai
    about: Read the documentation to get started.
  - name: Join our Discord
    url: https://discord.com/invite/6dffbvGU3D
    about: Join the Discord server to ask questions and get help.